const CHECKING_INTERVAL = 1000
const LAST_VALUES_NUMBER = 2
const MOVING_AVERAGE_INTERVAL = 5 * 60 * 1000 //5 min
const LAST_VALUES_MAX_PERCENT = 20 //20%

module.exports = {
    CHECKING_INTERVAL,
    LAST_VALUES_NUMBER,
    MOVING_AVERAGE_INTERVAL,
    LAST_VALUES_MAX_PERCENT
}